# Reusable Apple Silicon/Intel macOS -> Windows x86_64 MinGW toolchain.
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_CROSSCOMPILING TRUE)

get_filename_component(MAC2WIN_SDK_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
set(_MAC2WIN_DEFAULT_QT_MAJOR "6")
if(DEFINED ENV{MAC2WIN_QT_MAJOR})
    set(_MAC2WIN_DEFAULT_QT_MAJOR "$ENV{MAC2WIN_QT_MAJOR}")
endif()
set(MAC2WIN_QT_MAJOR "${_MAC2WIN_DEFAULT_QT_MAJOR}" CACHE STRING "Qt major version: 5 or 6")
set_property(CACHE MAC2WIN_QT_MAJOR PROPERTY STRINGS 5 6)
if(NOT MAC2WIN_QT_MAJOR MATCHES "^[56]$")
    message(FATAL_ERROR "MAC2WIN_QT_MAJOR must be 5 or 6")
endif()

find_program(MAC2WIN_BREW_EXECUTABLE brew REQUIRED)
execute_process(COMMAND "${MAC2WIN_BREW_EXECUTABLE}" --prefix mingw-w64
    OUTPUT_VARIABLE MAC2WIN_MINGW_PREFIX OUTPUT_STRIP_TRAILING_WHITESPACE
    COMMAND_ERROR_IS_FATAL ANY)

set(MAC2WIN_TRIPLET x86_64-w64-mingw32)
execute_process(COMMAND "${MAC2WIN_BREW_EXECUTABLE}" --prefix
    OUTPUT_VARIABLE MAC2WIN_HOMEBREW_PREFIX OUTPUT_STRIP_TRAILING_WHITESPACE
    COMMAND_ERROR_IS_FATAL ANY)
set(MAC2WIN_BIN_DIR "${MAC2WIN_HOMEBREW_PREFIX}/bin")

set(CMAKE_C_COMPILER "${MAC2WIN_BIN_DIR}/${MAC2WIN_TRIPLET}-gcc")
set(CMAKE_CXX_COMPILER "${MAC2WIN_BIN_DIR}/${MAC2WIN_TRIPLET}-g++")
set(CMAKE_RC_COMPILER "${MAC2WIN_BIN_DIR}/${MAC2WIN_TRIPLET}-windres")
set(CMAKE_AR "${MAC2WIN_BIN_DIR}/${MAC2WIN_TRIPLET}-ar")
set(CMAKE_RANLIB "${MAC2WIN_BIN_DIR}/${MAC2WIN_TRIPLET}-ranlib")
set(CMAKE_STRIP "${MAC2WIN_BIN_DIR}/${MAC2WIN_TRIPLET}-strip")

execute_process(COMMAND "${CMAKE_C_COMPILER}" -print-sysroot
    OUTPUT_VARIABLE CMAKE_SYSROOT OUTPUT_STRIP_TRAILING_WHITESPACE
    COMMAND_ERROR_IS_FATAL ANY)

set(MAC2WIN_QT_ROOT "${MAC2WIN_SDK_ROOT}/qt${MAC2WIN_QT_MAJOR}/package" CACHE PATH "Public Qt target SDK")
set(MAC2WIN_QT_CMAKEDEPS "${MAC2WIN_SDK_ROOT}/qt${MAC2WIN_QT_MAJOR}/conan")
list(PREPEND CMAKE_PREFIX_PATH "${MAC2WIN_QT_CMAKEDEPS}" "${MAC2WIN_QT_ROOT}")
list(PREPEND CMAKE_FIND_ROOT_PATH
    "${MAC2WIN_QT_CMAKEDEPS}"
    "${MAC2WIN_QT_ROOT}"
    "${CMAKE_SYSROOT}")

# Host executables (moc/uic/rcc/qsb) must run on macOS. Target libraries and
# application binaries are still compiled exclusively by MinGW GCC above.
if(MAC2WIN_QT_MAJOR STREQUAL "6")
    execute_process(COMMAND "${MAC2WIN_BREW_EXECUTABLE}" --prefix qt
        OUTPUT_VARIABLE QT_HOST_PATH OUTPUT_STRIP_TRAILING_WHITESPACE
        COMMAND_ERROR_IS_FATAL ANY)
endif()
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
